#!/bin/bash

MEMORY=150
DIR=""
MOUNTPOINT=""

MEM=0
for OPT in $* 
do
  if [ "$OPT" = "-m" ]; then
    MEM=1
  else 
    if [ "$MEM" = "1" ]; then
      MEMORY=$OPT
    else
      if [ "$DIR" = "" ]; then
        DIR="$OPT"
      else 
        if [ "$MOUNTPOINT" = "" ]; then
          MOUNTPOINT="$OPT"
        else 
          echo "usage: mp3cuefuse <source directory> <mount point>"
          exit 1
        fi
      fi
    fi
  fi
done

BN=`basename $0`
DN=`dirname $0`

LD_LIBRARY_PATH="$DN/mp3splt_sup/lib:$DN/mp3splt_sup/lib/libmp3splt0" mp3cuefuse_bin -m $MEMORY "$DIR" "$MOUNTPOINT" -o allow_other

